spring.application.name=users-service
server.port=8080
spring.session.jdbc.initialize-schema=always
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://users.chg2ekg2s786.ap-south-1.rds.amazonaws.com:5432/users
spring.datasource.username=postgres
spring.datasource.password=Users123#$
spring.jpa.hibernate.ddl-auto=update
jwt.secret=arn:aws:secretsmanager:ap-south-1:774489111931:secret:user/secrets-nYxFLT
jwt.expiration=86400000
spring.security.oauth2.client.registration.google.client-id=arn:aws:secretsmanager:ap-south-1:774489111931:secret:user/secrets-nYxFLT
spring.security.oauth2.client.registration.google.client-secret=arn:aws:secretsmanager:ap-south-1:774489111931:secret:user/secrets-nYxFLT
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# SSL Configuration (Required for RDS)
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

# For AWS ECS (when deployed to ECS)
eureka.client.service-url.defaultZone=http://service-register.extroverted-crocodile-uufy4z.local:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# In application.properties
management.endpoint.health.show-details=never
management.endpoints.web.exposure.include=health,info
# Don't check database in health endpoint
management.health.db.enabled=false  
# Don't check Eureka in health endpoint
management.health.eureka.enabled=false  
