spring.application.name=product-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://e-store-db.chg2ekg2s786.ap-south-1.rds.amazonaws.com:5432/e-store-db
spring.datasource.username=postgres
spring.datasource.password=Estore123#$
spring.jpa.hibernate.ddl-auto=update
server.port=8081

# AWS S3 Configuration
aws.access.key=AKIA3IUZF7V54KVYL6GT
aws.secret.key=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
aws.region=ap-south-1
aws.s3.bucket=productsimagesforestore
aws.s3.folder.products=products

# File upload configuration
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
spring.servlet.multipart.enabled=true

# SSL Configuration (Required for RDS)
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require