spring.application.name=Cart
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://carts.chg2ekg2s786.ap-south-1.rds.amazonaws.com:5432/carts
spring.datasource.username=postgres
spring.datasource.password=Carts123#$
spring.jpa.hibernate.ddl-auto=update
server.port=8082

# SSL Configuration (Required for RDS)
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
